const screenData = {
    "COMMON": [
        { category: "공통", menu1: "-", menu2: "-", id: "CM_CM_01_01", name: "진행중", type: "일반", date: "2026년", remarks: "" },
        { category: "공통", menu1: "-", menu2: "-", id: "CM_CM_01_02", name: "오류", type: "일반", date: "2026년", remarks: "" },
        { category: "서비스 접근", menu1: "-", menu2: "-", id: "CM_LG_01_01", name: "로그인", type: "일반", date: "2026년", remarks: "" },
        { category: "서비스 접근", menu1: "-", menu2: "-", id: "CM_LG_02_01", name: "서비스 이용 신청", type: "일반", date: "2026년", remarks: "" },
        { category: "서비스 접근", menu1: "-", menu2: "-", id: "CM_LG_03_01", name: "비밀번호 초기화 요청", type: "일반", date: "2026년", remarks: "" },
        { category: "서비스 접근", menu1: "-", menu2: "-", id: "CM_LG_03_02", name: "비밀번호 초기화 이메일", type: "이메일", date: "2026년", remarks: "" },
        { category: "서비스 접근", menu1: "-", menu2: "-", id: "CM_LG_03_03", name: "비밀번호 재설정", type: "일반", date: "2026년", remarks: "" },
        { category: "인트로", menu1: "-", menu2: "-", id: "CM_IT_01_01", name: "인트로", type: "일반", date: "2026년", remarks: "" },
        { category: "인트로", menu1: "-", menu2: "-", id: "CM_MB_01_01", name: "회원 정보", type: "일반", date: "2026년", remarks: "" },
        { category: "인트로", menu1: "-", menu2: "-", id: "CM_MB_01_02", name: "회원 정보 수정", type: "일반", date: "2026년", remarks: "" },
        { category: "인트로", menu1: "-", menu2: "-", id: "CM_MB_01_03", name: "비밀번호 변경", type: "모달", date: "2026년", remarks: "" },
    ],
    "IVMS": [
        { category: "메인 메뉴", menu1: "대시보드", menu2: "-", id: "IVM_DB_01_01", name: "IVMS 대시보드", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_01_01", name: "모니터링", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_02_01", name: "버티포트 상태 알림", type: "모달", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_03_01", name: "인프라 모니터링 알림", type: "모달", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_04_01", name: "이벤트 로그 목록", type: "모달", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_05_01", name: "운항 통계", type: "모달", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "IVM_MT_06_01", name: "비행계획서 모니터링", type: "모달", date: "2026년", remarks: "" },
        { category: "공지사항", menu1: "공지사항", menu2: "-", id: "IVM_CS_06_01", name: "공지사항 목록", type: "일반", date: "2026년", remarks: "" },
        { category: "공지사항", menu1: "공지사항", menu2: "-", id: "IVM_CS_06_02", name: "공지사항 열람", type: "일반", date: "2026년", remarks: "" },
    ],
    "IFPS": [
        { category: "비행 계획", menu1: "계획 수립", menu2: "-", id: "FP_01_01", name: "비행 계획서 작성", type: "일반", date: "2026년", remarks: "" },
        { category: "비행 계획", menu1: "계획 조회", menu2: "-", id: "FP_01_02", name: "비행 계획 목록", type: "일반", date: "2026년", remarks: "" },
        { category: "항로 관리", menu1: "항로 편집", menu2: "-", id: "FP_02_01", name: "3D 항로 편집기", type: "일반", date: "2026년", remarks: "" },
        { category: "기상 정보", menu1: "기상 조회", menu2: "-", id: "FP_03_01", name: "기상 정보 상세", type: "모달", date: "2026년", remarks: "" },
    ],
    "IFRS": [
        { category: "예약 관리", menu1: "예약 접수", menu2: "-", id: "RS_01_01", name: "신규 예약 접수", type: "일반", date: "2026년", remarks: "" },
        { category: "예약 관리", menu1: "예약 조회", menu2: "-", id: "RS_01_02", name: "통합 예약 목록", type: "일반", date: "2026년", remarks: "" },
        { category: "승객 관리", menu1: "체크인", menu2: "-", id: "RS_02_01", name: "모바일 체크인 현황", type: "일반", date: "2026년", remarks: "" },
        { category: "수하물", menu1: "추적", menu2: "-", id: "RS_03_01", name: "수하물 추적 모니터링", type: "일반", date: "2026년", remarks: "" },
    ],
    "V-CDM": [
        { category: "협업 관리", menu1: "메시지", menu2: "-", id: "VC_01_01", name: "기관 간 메시지 전송", type: "이메일", date: "2026년", remarks: "" },
        { category: "협업 관리", menu1: "회의", menu2: "-", id: "VC_01_02", name: "화상 회의실", type: "모달", date: "2026년", remarks: "" },
        { category: "상황 공유", menu1: "대시보드", menu2: "-", id: "VC_02_01", name: "실시간 상황판", type: "일반", date: "2026년", remarks: "" },
    ],
    "SAMS": [
        { category: "메인 메뉴", menu1: "대시보드", menu2: "-", id: "SAM_DB_01_01", name: "SAMS 대시보드", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "SAM_MO_01_01", name: "인프라 통합 현황", type: "일반", date: "2026년", remarks: "통합/연동/단독 서버 리스트 및 상태 값" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "SAM_MO_02_01", name: "하드웨어 모니터링", type: "모달", date: "2026년", remarks: "CPU/Mem/Disk 시계열 차트" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "SAM_MO_03_01", name: "네트워크 트래픽", type: "모달", date: "2026년", remarks: "패킷 손실, 지연시간 모니터링" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "SAM_MO_04_01", name: "인터페이스 현황", type: "모달", date: "2026년", remarks: "MQ 송수신, 트랜잭션 성공/실패 카운트" },
        { category: "메인 메뉴", menu1: "모니터링", menu2: "-", id: "SAM_MO_05_01", name: "데이터 인터페이스 현황", type: "모달", date: "2026년", remarks: "인터페이스별 메시지 큐 횟수, MQ 서버 송수신 현황, 데이터 트랜잭션 용량 정보" },
        { category: "메인 메뉴", menu1: "사용자 관리", menu2: "-", id: "SAM_US_01_01", name: "사용자 계정 관리", type: "일반", date: "2026년", remarks: "좌측: 사용자 목록 / 우측: 사용자 정보 | 회원정보, 상태(잠김해제/정지) 관리" },
        { category: "메인 메뉴", menu1: "사용자 관리", menu2: "-", id: "SAM_US_01_02", name: "사용자 계정 등록", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "사용자 관리", menu2: "-", id: "SAM_US_01_03", name: "사용자 계정 수정", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "사용자 관리", menu2: "-", id: "SAM_US_02_01", name: "사용자 계정 등록 이메일", type: "이메일", date: "2027년", remarks: "사용자 계정 등록 후 안내하는 이메일" },
        { category: "메인 메뉴", menu1: "권한/보안", menu2: "역할 정의", id: "SAM_AU_01_01", name: "역할 그룹 관리", type: "일반", date: "2026년", remarks: "좌측: 역할 목록 / 우측: 메뉴 트리(R/W 권한) | 슈퍼바이저, 운용자 등 역할(Role) ID/명칭 정의" },
        { category: "메인 메뉴", menu1: "권한/보안", menu2: "역할 정의", id: "SAM_AU_01_02", name: "역할 그룹 등록", type: "모달", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "권한/보안", menu2: "역할 배정", id: "SAM_AU_02_01", name: "역할 배정", type: "일반", date: "2026년", remarks: "좌측: 역할 / 우측: 사용자 매핑" },
        { category: "메인 메뉴", menu1: "권한/보안", menu2: "보안 정책 설정", id: "SAM_AU_03_01", name: "보안 정책 설정", type: "일반", date: "2026년", remarks: "세션 타임아웃 시간, 중복 로그인 허용 여부, 다중 로그인 허용 여부" },
        { category: "메인 메뉴", menu1: "로그 조회", menu2: "시스템 로그", id: "SAM_LG_01_01", name: "시스템 로그", type: "일반", date: "2026년", remarks: "시스템 로그 조회, 다운로드" },
        { category: "메인 메뉴", menu1: "로그 조회", menu2: "사용자 활동 로그", id: "SAM_LG_01_02", name: "사용자 활동 로그", type: "일반", date: "2026년~2027년", remarks: "2026년 로그인/로그아웃 로그 구현 | 2027년 C/U/D 행위 이력 추적 (로그인, 설정변경, 데이터 수정 등), 로그 조회, 다운로드" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "코드 관리", id: "SAM_SY_01_01", name: "공통 코드 관리", type: "일반", date: "2026년", remarks: "시스템 공통 코드 그룹 관리" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "코드 관리", id: "SAM_SY_01_02", name: "코드 등록", type: "모달", date: "2026년", remarks: "좌측: 코드 목록 / 우측: 코드 정보" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "장애 관리", id: "SAM_SY_02_01", name: "장애 이벤트 목록", type: "일반", date: "2026년", remarks: "실시간 장애 접수 현황" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "장애 관리", id: "SAM_SY_02_02", name: "장애 조치 등록", type: "모달", date: "2026년", remarks: "조치 내용 및 결과 입력" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "장애 관리", id: "SAM_SY_02_03", name: "알림/통지 설정", type: "일반", date: "2027년", remarks: "등급별 SMS/Email 수신자 설정" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "백업 설정", id: "SAM_SY_03_01", name: "백업 설정", type: "일반", date: "2026년", remarks: "데이터 백업 정책 설정 : 백업 주기(일/주), 보관 기간 설정, 백업 스케줄 설정" },
        { category: "메인 메뉴", menu1: "시스템 운영", menu2: "백업 이력", id: "SAM_SY_04_01", name: "백업 이력", type: "일반", date: "2027년", remarks: "좌측: 백업 파일 목록, 우측 백업 내역('복구' 실행 버튼)" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "버티포트", id: "SAM_AS_01_01", name: "버티포트 관리", type: "일반", date: "2026년", remarks: "좌측: 목록, 우측: 버티포트 정보 | 기본정보, 시설 정보(FATO, STAND, 충전/격납/계류장 체크) 구성" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "버티포트", id: "SAM_AS_01_02", name: "버티포트 등록", type: "일반", date: "2027년", remarks: "" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "운항사", id: "SAM_AS_02_01", name: "운항사 관리", type: "일반", date: "2027년", remarks: "트리 구조(운항사->기체)로 관리" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "기체 관리", id: "SAM_AS_03_01", name: "기체 관리", type: "일반", date: "2027년", remarks: "기체 등록 시, 운항사 선택" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "교통 관리자", id: "SAM_AS_04_01", name: "교통 관리자", type: "일반", date: "2027년", remarks: "" },
        { category: "메인 메뉴", menu1: "연계 시스템 관리", menu2: "도심항공 교통 정보 시스템", id: "SAM_AS_05_01", name: "도심항공 교통 정보 시스템", type: "일반", date: "2027년", remarks: "" },
        { category: "메인 메뉴", menu1: "연계 시스템 운영", menu2: "연계 상태 모니터링", id: "SAM_AS_10_01", name: "연계 상태 모니터링", type: "일반", date: "2027년", remarks: "요약 정보, 검색(상태, 연계 시스템, 토픽, 조회 기간, 키워드:메시지 전문), 큐 목록" },
        { category: "메인 메뉴", menu1: "연계 시스템 운영", menu2: "실패 메시지 관리 (DLQ)", id: "SAM_AS_11_01", name: "실패 메시지 관리 (DLQ)", type: "일반", date: "2027년", remarks: "" },
        { category: "메인 메뉴", menu1: "연계 시스템 운영", menu2: "연계 시스템 통계", id: "SAM_AS_12_01", name: "연계 시스템 통계", type: "일반", date: "2027년", remarks: "" },
        { category: "메인 메뉴", menu1: "공지사항 관리", menu2: "-", id: "SAM_BD_01_01", name: "공지사항 목록", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "공지사항 관리", menu2: "-", id: "SAM_BD_01_02", name: "공지사항 등록", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "공지사항 관리", menu2: "-", id: "SAM_BD_01_03", name: "공지사항 열람", type: "일반", date: "2026년", remarks: "" },
        { category: "메인 메뉴", menu1: "공지사항 관리", menu2: "-", id: "SAM_BD_01_04", name: "공지사항 수정", type: "일반", date: "2026년", remarks: "" },
    ]
};
